version: '3'

networks:
  gm_highload-network:
    driver: bridge

services:

        gm_highload:
            build:
                context: php-fpm
                args:
                    - timezone=${TZ}
            networks:
                - gm_highload-network
            volumes:
                - ./../gm_highload:/gm_highload:rw,cached
                - gm_highload_log:/gm_highload/var/log
            env_file:
                - .env
            depends_on:
                - redis
                - memcached
                - mariadb
                - percona

        nginx:
            container_name: nginx
            build:
                context: nginx
                args:
                    - timezone=${TZ}
            ports:
                - "80:80"
                - "443:443"
            networks:
                - gm_highload-network
            depends_on:
                - gm_highload
            volumes:
                - ./../gm_highload/public:/gm_highload/public
                - ./nginx/ssl:/etc/nginx/ssl
                - ./nginx/conf.d:/etc/nginx/conf.d
                - ./nginx/nginx_log:/var/log/nginx
                - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            env_file:
                - .env
            command: /bin/bash -c "exec nginx -g 'daemon off;'"

        redis:
            container_name: redis
            image: redis:latest
            ports:
                - "6379:6379"
            networks:
                - gm_highload-network

        memcached:
            container_name: memcached
            image: memcached:latest
            ports:
                    - "11211:11211"
            networks:
                - gm_highload-network

        mariadb:
            container_name: mariadb
            image: mariadb:latest
            env_file:
                - maria/master/.env.master
            ports:
                - "3307:3306"
            volumes:
                - ./maria/master/.data/mysql:/var/lib/mysql:rw
            networks:
                - gm_highload-network

        percona:
            container_name: percona
            image: percona:latest
            env_file:
                - percona/master/.env.master
            ports:
                - "3308:3306"
#            volumes:
#                - ./percona/master/.data/mysql:/var/lib/mysql:rw
            networks:
                - gm_highload-network

volumes:
    nginx_log:
    gm_highload_log:
    db:
        driver: local
